### ISSUE TITLE
Import/require class from github

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#5]
Would be nice to be able to require a class directly from a repo in github.
For example: [https://github.com/dhowe/annograms/blob/main/annogram.js](https://github.com/dhowe/annograms/blob/main/annogram.js)

I've tried unsuccessfully with import, next will try with require...

**Comment by dhowe** [comment]
Apparently it can be done as follows (from [this](https://talk.observablehq.com/t/import-a-module-from-github/605/2) forum):

```js
geo2rect = {
  const response = await fetch("https://raw.githubusercontent.com/sebastian-meier/d3.geo2rect/master/build/geo2rect.min.js");
  const blob = await response.blob();
  return require(URL.createObjectURL(blob)).catch(() => window.geo2rect);
}
```

**Comment by Real-John-Cheung** [comment]
github set the MIME type of the file to `text/plain`, so maybe we need to load it via jsDelivr or something, like this
```js
Annogram = await import("https://cdn.jsdelivr.net/gh/dhowe/annograms/annogram.js")
```
but then the first line in `annogram.js` will cause error since there is no context for `rita`

I did a tricky workaround and it works (somehow), like this
```js
AnnogramGithub = {
  const res = await fetch("https://raw.githubusercontent.com/dhowe/annograms/main/annogram.js");
  let text = await res.text();
  text = text.replace(/^import[ A-Za-z"'\{\}]+;/,"");
  const newBlob = new Blob([text],{type: 'text/javascript'});
  const m = await import(URL.createObjectURL(newBlob));
  return m.Annogram;
}
```
The class seems to be loaded successfully, since its property can be read correctly
![圖片](https://user-images.githubusercontent.com/61215358/147559647-b8672c64-7aed-4512-8afd-759637d9ae4d.png)
but for some reason it cannot get access to RiTa which is imported independently on the page...
![圖片](https://user-images.githubusercontent.com/61215358/147559742-829b4fed-4c48-41f2-ba6b-22bcd3128f21.png)

**Comment by Real-John-Cheung** [comment]
a hack that work (but need to change the structure of the class a bit):
see https://observablehq.com/d/c61c94dc0b89fb4b and https://github.com/Real-John-Cheung/annograms/blob/issue%235/annogram.js

**Comment by dhowe** [comment]
nice (temporary) fix
